name: Update GitHub Profile

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use the PAT instead of GITHUB_TOKEN

  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch latest blog post
        id: fetch_blog
        run: |
          BLOG_POST=$(curl -s https://dyst0rti0n.github.io/feed.xml | grep -oPm1 "(?<=<link>)[^<]+" | sed -n '2p')
          BLOG_TITLE=$(curl -s https://dyst0rti0n.github.io/feed.xml | grep -oPm1 "(?<=<title>)[^<]+" | sed -n '2p')
          echo "::set-output name=blog_post::$BLOG_POST"
          echo "::set-output name=blog_title::$BLOG_TITLE"

      - name: Update README
        run: |
          sed -i "s|<!-- BLOG_SECTION_START -->.*<!-- BLOG_SECTION_END -->|<!-- BLOG_SECTION_START -->\n- [${{ steps.fetch_blog.outputs.blog_title }}](${{ steps.fetch_blog.outputs.blog_post }})\n<!-- BLOG_SECTION_END -->|" README.md

      - name: Fetch Golang learning path
        id: fetch_learning_path
        run: |
          LEARNING_PATH_URL="https://dyst0rti0n.github.io/academy/golang-path.html"
          LEARNING_PATH_TITLE="Golang Learning Path"
          echo "::set-output name=learning_path_url::$LEARNING_PATH_URL"
          echo "::set-output name=learning_path_title::$LEARNING_PATH_TITLE"

      - name: Update README with Golang learning path
        run: |
          sed -i "s|<!-- LEARNING_PATH_SECTION_START -->.*<!-- LEARNING_PATH_SECTION_END -->|<!-- LEARNING_PATH_SECTION_START -->\n- [${{ steps.fetch_learning_path.outputs.learning_path_title }}](${{ steps.fetch_learning_path.outputs.learning_path_url }})\n<!-- LEARNING_PATH_SECTION_END -->|" README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest blog post and learning path"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
